# Generated by Django 6.0.5 on 2026-05-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='post',
            field=models.ManyToManyField(related_name='hashtag', to='posts.post'),
        ),
    ]
