# Generated by Django 6.0.5 on 2026-05-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_hashtag_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='post',
            field=models.ManyToManyField(related_name='hashtags', to='posts.post'),
        ),
    ]
