# Generated by Django 6.0.5 on 2026-05-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_hashtag_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='body',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
