# Generated by Django 6.0.5 on 2026-05-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_hashtag_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='post',
            new_name='posts',
        ),
    ]
