# Generated by Django 6.0.5 on 2026-05-11 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='story',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['created_at'], name='stories_sto_created_d8706d_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['user'], name='stories_sto_user_id_9909a1_idx'),
        ),
    ]
