# Generated by Django 6.0.5 on 2026-05-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_options_alter_story_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
