# Generated by Django 6.0.5 on 2026-05-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='story',
            name='stories_sto_created_d8706d_idx',
        ),
        migrations.RemoveIndex(
            model_name='story',
            name='stories_sto_user_id_9909a1_idx',
        ),
        migrations.AddField(
            model_name='story',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='story',
            name='is_active',
        ),
    ]
