# Generated by Django 6.0.5 on 2026-05-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directconversation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='directmessage',
            options={'ordering': ['created_at']},
        ),
    ]
